FROM python:3.9-slim

ADD . /app
WORKDIR /app

RUN apt update
RUN apt -y upgrade
RUN apt -y install python3 python3-pip

COPY requirements.txt /app
RUN pip3 install -r requirements.txt
COPY app.py /app

EXPOSE 5000

CMD python app.py
